-- MySQL Script generated by MySQL Workbench
-- Sat Feb  8 18:59:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Class
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Class
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Class` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Class` ;

-- -----------------------------------------------------
-- Table `Class`.`centers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`centers` (
  `ID` SMALLINT NOT NULL,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  `phone` CHAR(11) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `governorate` VARCHAR(14) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Class`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`users` (
  `ID` MEDIUMINT NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `pws` VARCHAR(255) NOT NULL,
  `phone` CHAR(11) NULL DEFAULT NULL,
  `rule` ENUM('std', 'admin', 'teacher') NULL DEFAULT 'std',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `unique_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Class`.`videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`videos` (
  `ID` SMALLINT NOT NULL,
  `weekNum` SMALLINT NULL DEFAULT NULL,
  `title` VARCHAR(250) NULL DEFAULT NULL,
  `year` CHAR(4) NULL DEFAULT NULL,
  `video_Path` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `idx_year_videos` (`year` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Class`.`edit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`edit` (
  `user_ID` MEDIUMINT NOT NULL,
  `video_ID` SMALLINT NOT NULL,
  PRIMARY KEY (`user_ID`, `video_ID`),
  INDEX `fk_videoEdit` (`video_ID` ASC) VISIBLE,
  CONSTRAINT `fk_userEdit`
    FOREIGN KEY (`user_ID`)
    REFERENCES `Class`.`users` (`ID`),
  CONSTRAINT `fk_videoEdit`
    FOREIGN KEY (`video_ID`)
    REFERENCES `Class`.`videos` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Class`.`requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`requirements` (
  `ID` SMALLINT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(10) NULL DEFAULT NULL,
  `title` VARCHAR(250) NULL DEFAULT NULL,
  `year` CHAR(4) NULL DEFAULT NULL,
  `filePath` VARCHAR(255) NULL DEFAULT NULL,
  `duration` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `idx_year_tasks` (`year` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Class`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`schedules` (
  `ID` SMALLINT NOT NULL,
  `day` ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') NULL DEFAULT NULL,
  `clock` TIME NULL DEFAULT NULL,
  `center_ID` SMALLINT NULL DEFAULT NULL,
  `year` CHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_center` (`center_ID` ASC) VISIBLE,
  CONSTRAINT `fk_center`
    FOREIGN KEY (`center_ID`)
    REFERENCES `Class`.`centers` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Class`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`students` (
  `ID` MEDIUMINT NOT NULL,
  `firstName` VARCHAR(30) NULL DEFAULT NULL,
  `middleName` VARCHAR(30) NULL DEFAULT NULL,
  `lastName` VARCHAR(30) NULL DEFAULT NULL,
  `parentPhone` CHAR(11) NULL DEFAULT NULL,
  `year` CHAR(4) NULL DEFAULT NULL,
  `center_ID` SMALLINT NULL DEFAULT NULL,
  `schedule_ID` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_usercenter` (`center_ID` ASC) VISIBLE,
  INDEX `fk_userschdule` (`schedule_ID` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`ID`)
    REFERENCES `Class`.`users` (`ID`),
  CONSTRAINT `fk_usercenter`
    FOREIGN KEY (`center_ID`)
    REFERENCES `Class`.`centers` (`ID`),
  CONSTRAINT `fk_userschdule`
    FOREIGN KEY (`schedule_ID`)
    REFERENCES `Class`.`schedules` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Class`.`submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`submissions` (
  `ID` SMALLINT NOT NULL AUTO_INCREMENT,
  `filePath` VARCHAR(255) NULL DEFAULT NULL,
  `submittedTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `required_ID` SMALLINT NULL DEFAULT NULL,
  `std_ID` MEDIUMINT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_requirement` (`required_ID` ASC) VISIBLE,
  INDEX `fk_sub_std` (`std_ID` ASC) VISIBLE,
  CONSTRAINT `fk_requirement`
    FOREIGN KEY (`required_ID`)
    REFERENCES `Class`.`requirements` (`ID`),
  CONSTRAINT `fk_sub_std`
    FOREIGN KEY (`std_ID`)
    REFERENCES `Class`.`students` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Class`.`watch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Class`.`watch` (
  `user_ID` MEDIUMINT NOT NULL,
  `video_ID` SMALLINT NOT NULL,
  PRIMARY KEY (`user_ID`, `video_ID`),
  INDEX `fk_videoAccess` (`video_ID` ASC) VISIBLE,
  CONSTRAINT `fk_userAccess`
    FOREIGN KEY (`user_ID`)
    REFERENCES `Class`.`users` (`ID`),
  CONSTRAINT `fk_videoAccess`
    FOREIGN KEY (`video_ID`)
    REFERENCES `Class`.`videos` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
